version: "3"

services:
  redis-server:
    image: "redis"
    restart: always
    ports:
      - "6379:6379"
  database:
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
