version: "3"

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis-server
      - database
  redis-server:
    image: "redis"
    restart: always
    ports:
      - "6379:6379"
  database:
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432" 
